using System;
using System.Data;

namespace Nemo
{
    public class Param
    {
        public Param()
        {
            Direction = ParameterDirection.Input;
            Size = -1;
        }

        public Param(Param parameter)
        {
            Name = parameter.Name;
            Direction = parameter.Direction;
            Value = parameter.Value;
            DbType = parameter.DbType;
            Size = parameter.Size;
        }

        public Param(IDataParameter parameter)
        {
            Name = parameter.ParameterName;
            Direction = parameter.Direction;
            Value = parameter.Value;
            DbType = parameter.DbType;
        }

        public Param(IDbDataParameter parameter)
        {
            Name = parameter.ParameterName;
            Direction = parameter.Direction;
            Value = parameter.Value;
            DbType = parameter.DbType;
            Size = parameter.Size;
        }

        public string Name { get; set; }
        public ParameterDirection Direction { get; set; }
        public object Value { get; set; }
        public DbType? DbType { get; set; }
        public Type Type
        {
            get
            {
                return Value != null ? Value.GetType() : null;
            }
        }
        public int Size { get; set; }
        public string Source { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsPrimaryKey { get; set; }
    }
}
